# Generated by Django 6.0.1 on 2026-07-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_course_subject_chapter_lesson_lessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentactivity',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentstreak',
            name='student',
        ),
        migrations.DeleteModel(
            name='AIChatMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='StudentActivity',
        ),
        migrations.DeleteModel(
            name='StudentStreak',
        ),
    ]
