# Generated by Django 6.0.5 on 2026-06-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('login', 'Login'), ('password_reset', 'Password Reset')], default='email_verification', max_length=30),
        ),
    ]
