# Generated by Django 6.0.1 on 2026-08-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_completed_at_enrollment_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
