# Generated by Django 6.0.1 on 2026-08-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_transcript_lesson_transcript_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='original_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
