# Generated by Django 6.0.1 on 2026-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_original_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
