# Generated by Django 6.0.1 on 2026-08-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('upload', 'Uploaded')], default='youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
    ]
