# Generated by Django 6.0.1 on 2026-07-13 16:47

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupmember_groupmessage'),
    ]

    operations = [

        migrations.RenameField(
            model_name="chatroom",
            old_name="student",
            new_name="user1",
        ),
        migrations.RenameField(
            model_name="chatroom",
            old_name="mentor",
            new_name="user2",
        ),
        migrations.RenameField(
            model_name="groupchat",
            old_name="mentor",
            new_name="created_by",
        ),
        migrations.AddField(
            model_name="groupchat",
            name="group_type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("student_batch", "Student Batch"),
                    ("mentor_group", "Mentor Group"),
                ],
                default="student_batch",
            ),
        ),
        migrations.RenameField(
            model_name="groupmember",
            old_name="student",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("group", "user")},
        ),

    ]
