# Generated by Django 6.0.1 on 2026-07-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_user1_alter_chatroom_user2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Broadcast',
        ),
    ]
